### ISSUE TITLE
Support for picking alpha

### ISSUE THREAD

**Issue by kabiroberai** [hbang/Alderis#1]
It would be great to have the ability for users to customize a color's alpha value. As for the way that this is represented in the picker's chrome, perhaps higher alpha values could begin revealing a "checkerboard" underneath the nav/bottom bar? Or alternatively, just don't represent the alpha in the chrome at all.

**Comment by Macley-Kun** [comment]
Alpha is supported atm, any reason to keep this one up?

**Comment by kirb** [comment]
It’s not currently supported, transparent colors will become opaque. It’s half-implemented for the 1.1 release via Kabir’s PR in #3, won’t become opaque but there’s no slider for adjusting alpha yet.

**Comment by CobreDev** [comment]
I noticed this issue hasn't been active since May 4, any updates? I'd really like to use Alderis, but I need to be able to set Alpha

**Comment by kirb** [comment]
Implemented in 1.1
