### ISSUE TITLE
Auto-detect and select the current color in color palette

### ISSUE THREAD

**Issue by p0358** [hbang/Alderis#11]
Steps to reproduce:
1. Open the color picker in some tweak's settings
2. Select a predefined color in the color palette (the first tab)
![obraz](https://user-images.githubusercontent.com/5182588/83806976-999fd600-a6b2-11ea-8b48-dbf24be3b0c4.png)
3. Hit Done
4. Open the color picker again

Expected behavior:
5. The previously selected color would remain selected on the color palette (or if the entered hex code matches one of these presets), like in the step 2 above

Actual behavior:
5. Nothing is selected at all. The top and bottom bars themselves are colored accordingly though.

**Comment by kirb** [comment]
I believe this is fixed in #3, which will be released in version 1.1 soon. However I’ll keep this open as a reminder to test it.

**Comment by kirb** [comment]
Should be fixed in 1.1.
