### ISSUE TITLE
[Swift Package Manager] Failed to resolve dependencies

### ISSUE THREAD

**Issue by rostopira** [hbang/Alderis#15]
I'm trying to add this library via swift package manager in XCode 12
I'm getting following error:
```
because no versions of Alderis match the requirement 1.0.0..<2.0.0 and root depends on Alderis 1.0.0..<2.0.0, version solving failed.
```
I've tried 1.0, 1.1, next minor, next major
No luck

**Comment by kirb** [comment]
Seems SPM wants exactly 3 digits (1.1.0), while the tag only has two (1.1). I just pushed tag 1.1.0 pointing to the same commit as 1.1, it seems to work now. Let me know how you go.

**Comment by kirb** [comment]
Closing as I believe this is fixed.
