### ISSUE TITLE
Custom HEX code

### ISSUE THREAD

**Issue by Macley-Kun** [hbang/Alderis#2]
Like where this solution is going!
It would be great to be able to paste a hexcode I have in my clipboard, instead of looking up the respectable RGB/HSB values.

**Comment by kirb** [comment]
The hex field is editable. Just tap in it. It does need a better way of showing it’s editable… not sure what way I can show that without it looking too intrusive.

**Comment by kabiroberai** [comment]
Seems like it doesn't let me type out hex codes atm (at least after the refactor made in #3)

**Comment by Macley-Kun** [comment]
I can select it indeed, and yes the keyboard shows up.
But i cannot edit that string in any way.
![IMG_0283](https://user-images.githubusercontent.com/26381427/77351130-a2347180-6d3d-11ea-8bd6-09ca32023ae2.jpg)

**Comment by kabiroberai** [comment]
This should be fixed by 2dda34c

**Comment by Macley-Kun** [comment]
I'll keep an eye out of the next update! Will report back status about it :-)

Thanks dude!

**Comment by Macley-Kun** [comment]
Gonna close this, sorry for the late reply!
UI looks amazing btw! Hope all the other colorpickers are gonna be deprecated soon!
