### ISSUE TITLE
libcolorpicker compat fails to link

### ISSUE THREAD

**Issue by Mukul1127** [hbang/Alderis#28]
When using the 16.4 SDK from https://github.com/xybp888/iOS-SDKs, I keep getting this:
```
 ==> Linking library libcolorpicker (arm64)…
ld: warning: ignoring duplicate libraries: '-lc++'
ld: warning: search path '/Users/runner/work/uYouEnhancedBuild/uYouEnhancedBuild/main/.theos/obj/install/Library/Frameworks' not found
ld: warning: search path '/Users/runner/work/uYouEnhancedBuild/uYouEnhancedBuild/main/.theos/obj/install/var/jb/Library/Frameworks' not found
ld: framework 'Preferences' not found
```
But when I use a 17.0.3 SDK from the same repo, it works even though both do not seem to have a `Preferences.framework` folder.

Any help would be nice

**Comment by kirb** [comment]
You need to use a patched SDK with private frameworks from https://github.com/theos/sdks.

**Comment by Mukul1127** [comment]
It is patched + I already tried 16.5 from theos repo and got same error

**Comment by kirb** [comment]
Ah I see the issue, you’ll need to set `TARGET` to specify the SDK version. Depending if you’re building for rootful or rootless, it’ll be either line 3 or 7 of the main Makefile. Where it says `latest`, change it to the SDK version you’re using. Then do `make clean` and try again.

**Comment by Mukul1127** [comment]
> Ah I see the issue, you’ll need to set `TARGET` to specify the SDK version. Depending if you’re building for rootful or rootless, it’ll be either line 3 or 7 of the main Makefile. Where it says `latest`, change it to the SDK version you’re using. Then do `make clean` and try again.

Thanks, this fixed everything
