### ISSUE TITLE
Cannot link libcolorpicker

### ISSUE THREAD

**Issue by X1nto** [hbang/Alderis#29]
The linker cannot find Preferences.framework. I'm using the 16.5 patched SDK from [theos](https://github.com/theos/sdks), but the build always seems to default to the latest SDK (17.5 for me, which isn't patched) available on the system as xcodebuild is run with `--sdk-root /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.5.sdk`.

```sh
==> Linking library libcolorpicker (arm64)…
ld: warning: -multiply_defined is obsolete
ld: warning: search path '/Users/Xinto/uYouPlus/.theos/obj/install/Library/Frameworks' not found
ld: warning: search path '/Users/Xinto/uYouPlus/.theos/obj/install/var/jb/Library/Frameworks' not found
ld: framework 'Preferences' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [/Users/Xinto/theos/makefiles/instance/library.mk:52: /Users/Xinto/uYouPlus/.theos/obj/arm64/libcolorpicker.dylib] Error 1
make[4]: *** [/Users/Xinto/theos/makefiles/instance/library.mk:52: /Users/Xinto/uYouPlus/.theos/obj/arm64/libcolorpicker.dylib] Error 2
make[3]: *** [/Users/Xinto/theos/makefiles/instance/library.mk:37: internal-library-all_] Error 2
make[2]: *** [/Users/Xinto/theos/makefiles/master/rules.mk:146: libcolorpicker.all.library.variables] Error 2
make[1]: *** [/Users/Xinto/theos/makefiles/master/aggregate.mk:12: internal-all] Error 2
make: *** [/Users/Xinto/theos/makefiles/master/aggregate.mk:12: internal-all] Error 2
```

`make clean` outputs the following:
```sh
Build settings from command line:
    ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = NO
    ARCHS = arm64
    BUILD_LIBRARY_FOR_DISTRIBUTION = YES
    CODE_SIGNING_ALLOWED = NO
    DSTROOT = /Users/Xinto/uYouPlus/.theos/obj/debug/install_Alderis
    DYLIB_INSTALL_NAME_BASE = @rpath
    ENABLE_BITCODE = NO
    LD_DYLIB_INSTALL_NAME = @rpath/Alderis.framework/Alderis
    LOCAL_LIBRARY_DIR = /Library
    SDKROOT = iphoneos17.5
    STRIP_INSTALLED_PRODUCT = NO
```

I set the `TARGET` to `iphone:clang:16.5:14.5`, however, Alderis still uses 17.5.

```make
export TARGET = iphone:clang:16.5:14.5
```

Sorry if this isn't related to Alderis or libcolorpicker, but I couldn't find references to other issues in the logs.

**Comment by X1nto** [comment]
Fixed by adding
```make
export SDK_PATH = $(THEOS)/sdks/iPhoneOS16.5.sdk/
export SYSROOT = $(SDK_PATH)
```
under `export TARGET`

Here's how the final export looks like:
```make
export TARGET = iphone:clang:16.5:14.5
export SDK_PATH = $(THEOS)/sdks/iPhoneOS16.5.sdk/
export SYSROOT = $(SDK_PATH)
```

**Comment by Mukul1127** [comment]
I believe the "correct fix" is https://github.com/hbang/Alderis/issues/28

**Comment by Mukul1127** [comment]
As I see it, you are basically forcing Xcode to use 17.5 to compile and 16.5 to link??? Please correct me if I'm wrong but that seems to be what's happening.

**Comment by kirb** [comment]
Theos and Xcode use different build configs. You should have no issue building with latest SDK with the Xcode side of the project (assuming you don’t need to support iOS 12-13 arm64e). The Theos side needs a patched SDK with Preferences.framework defined. If you don’t use libcolorpicker compatibility or Preferences integration, then you can skip building lcpshim by commenting out the `SUBPROJECTS = lcpshim` line in Makefile.

**Comment by X1nto** [comment]
The problem is that it grabs the unpatched 17.5 SDK, even though I've specified 16.5 in the TARGET export. I don't understand why it tries to compile with 17.5, but explicit SYSROOT and SDK_PATH solve the issue. I assume it's a bug in Theos. Thanks for suggesting the lcpshim part though, helps a lot.
