### ISSUE TITLE
Color pallate incompatible with right to left aligned languages

### ISSUE THREAD

**Issue by Aransh** [hbang/Alderis#9]
When using the color pallate (on Scorpion), whichever color I tap will select the color in the mirrored location (as in, tap blue in right edge, get green in left edge selected).

**Comment by kabiroberai** [comment]
This should have been fixed by #3, as I changed it to use `hitTest` rather than calculating the color itself (see ColorPickerSwatchViewController.swift:249)

**Comment by kirb** [comment]
This should be fixed with 1.1. Due to the way I changed the implementation, the palette/swatch will no longer flip right-to-left for RTL languages. I may add RTL support back in a future release.
